name: 🧪 Test Release

on:
  pull_request:
    branches: ["main", "release/**"]
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ${{ vars.CI_RUNNER_LIGHT || 'ubuntu-latest' }}
    permissions:
      contents: read

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: ⚙️ Install bun
        uses: oven-sh/setup-bun@v2

      - name: 🔨 Install package globally
        run: bun install -g @airfleet/wordpress-dev

      - name: 🔬 Check version increment
        run: afwp version-set --check

      - name: 🔬 Check changelog entries
        run: afwp changelog-add --check
